[package]
name = "example_custom_render"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.10", default_features = false }
bevy_pixels = { path = "../../", default_features = false }
